name: Docker Build and Push

on:
  push:
    branches: [ master, main, dev-docker-actions ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image train_model
      uses: docker/build-push-action@v2
      with:
        push: true
        file: ./dockerfiles/train_model.dockerfile
        tags: ghcr.io/corusm/train_model:latest

    - name: Build and push Docker image predict_model
      uses: docker/build-push-action@v2
      with:
        push: true
        file: ./dockerfiles/predict_model.dockerfile
        tags: ghcr.io/corusm/predict_model:latest
