name: Docker Build and Push

on:
  push:
    branches: [ master, main, dev-gpucontainer ]
env:
  PROJECT_ID: dtumlops-g62v2
  PROJECT_NO: 311990494126

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        create_credentials_file: 'true'
        workload_identity_provider: 'projects/${{env.PROJECT_NO}}/locations/global/workloadIdentityPools/gh-identity-pool/providers/gh-provider'
        token_format: 'access_token'
        service_account: 'gcp-github-access@${{env.PROJECT_ID}}.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'

    - uses: iterative/setup-dvc@v1
    - name: Get data
      run: dvc pull

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image train_model
      uses: docker/build-push-action@v2
      with:
        push: true
        file: ./dockerfiles/train_model.dockerfile
        tags: ghcr.io/corusm/train_model:latest

    - name: Build and push Docker image train_model GPU
      uses: docker/build-push-action@v2
      with:
        push: true
        file: ./dockerfiles/train_model.gpu.dockerfile
        tags: ghcr.io/corusm/train_model-gpu:latest

    - name: Build and push Docker image predict_model
      uses: docker/build-push-action@v2
      with:
        push: true
        file: ./dockerfiles/predict_model.dockerfile
        tags: ghcr.io/corusm/predict_model:latest
