name: "Run tests"

on:
  push:
    branches: [ master, main, dvc-gh-actions ] # remove before merge!
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    # TODO: remove when setup
    - name: Debug GCP Credentials
      run: |
        echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' | base64 -d > gcp-credentials.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcp-credentials.json" >> $GITHUB_ENV

    # TODO uncomment when the dvc will be set up
    - uses: iterative/setup-dvc@v1
    - name: Get data
      run: dvc pull
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    # - name: Cache Python dependecies
    #   uses: actions/cache@v2
    #   with:
    #     path: ~/.cache/pip
    #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/requirements_tests.txt') }}
    #     restore-keys: |
    #       ${{ runner.os }}-pip-

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt
    #     pip install -r requirements_tests.txt

    # - name: Test with pytest
    #   run: |
    #     pip install pytest
    #     pytest -v
