name: "Run tests"

on:
  push:
    branches: [ master, main, dvc-gh-actions ] # remove before merge!
  pull_request:
    branches: [ master, main ]
env:
  PROJECT_ID: dtumlops-g62v2
  PROJECT_NO: 311990494126


jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        create_credentials_file: 'true'
        workload_identity_provider: 'projects/${{env.PROJECT_NO}}/locations/global/workloadIdentityPools/gh-identity-pool/providers/gh-provider'
        token_format: 'access_token'

        # Below are from the above terraform code 
        # workloadIdentityPools = gh-identity-pool
        # providers/gh-provider'

        service_account: 'gcp-github-access@${{env.PROJECT_ID}}.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'

    - uses: iterative/setup-dvc@v1
    - name: Get data
      run: dvc pull
    # resource: https://github.com/google-github-actions/auth#preferred-direct-workload-identity-federation
    # github issue: https://github.com/iterative/cml/issues/862#issuecomment-1107689427
    # tutorial: https://medium.com/google-cloud/keyless-authentication-to-google-cloud-from-github-actions-with-workload-identity-federation-605e725b51d


    - name: Cache Python dependecies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/requirements_tests.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_tests.txt

    - name: Test with pytest
      run: |
        pip install pytest
        pytest -v
