name: "Run tests"

on:
  push:
    branches: [ master, main, dvc-gh-actions ] # remove before merge!
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Login
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}

    - uses: iterative/setup-dvc@v1
    - name: Get data
      run: dvc pull
      # resource: https://github.com/google-github-actions/auth#preferred-direct-workload-identity-federation
      # github issue: https://github.com/iterative/cml/issues/862#issuecomment-1107689427


    # - name: Cache Python dependecies
    #   uses: actions/cache@v2
    #   with:
    #     path: ~/.cache/pip
    #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/requirements_tests.txt') }}
    #     restore-keys: |
    #       ${{ runner.os }}-pip-

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt
    #     pip install -r requirements_tests.txt

    # - name: Test with pytest
    #   run: |
    #     pip install pytest
    #     pytest -v
